#include <iostream>
#include <vector>
#include <cmath>
using namespace std;

// Enum to describe prime status
enum PrimeStatus {
    PRIME,
    NOT_PRIME_DIVISIBLE,
    NOT_PRIME_LESS_THAN_2
};

// Detailed primality check with reason
PrimeStatus isPrimeDetailed(int n, int& divisor) {
    if (n < 2) {
        divisor = -1;
        return NOT_PRIME_LESS_THAN_2;
    }
    for (int i = 2; i <= sqrt(n); ++i) {
        if (n % i == 0) {
            divisor = i;
            return NOT_PRIME_DIVISIBLE;
        }
    }
    return PRIME;
}

int main() {
    int choice;
    while (true) {
        cout << "\n===== HASANI PRIME SIEVE =====\n";
        cout << "1 - Check if a number is prime\n";
        cout << "2 - Generate primes in a range\n";
        cout << "3 - Analyze primality structurally (+/-10 range)\n";
        cout << "0 - Exit\n";
        cout << "Your choice: ";
        cin >> choice;

        if (choice == 0) break;

        else if (choice == 1) {
            int num, reason = -1;
            cout << "Enter number to check: ";
            cin >> num;
            PrimeStatus status = isPrimeDetailed(num, reason);

            if (status == PRIME)
                cout << num << " is PRIME.\n";
            else if (status == NOT_PRIME_LESS_THAN_2)
                cout << num << " is NOT prime (less than 2).\n";
            else
                cout << num << " is NOT prime (divisible by " << reason << ").\n";
        }

        else if (choice == 2) {
            int start, end;
            cout << "Enter start and end of range: ";
            cin >> start >> end;

            cout << "Primes in range [" << start << ", " << end << "]:\n";
            for (int x = start; x <= end; ++x) {
                int reason = -1;
                if (isPrimeDetailed(x, reason) == PRIME)
                    cout << x << " ";
            }
            cout << "\n";
        }

        else if (choice == 3) {
            int num;
            cout << "Enter number to analyze: ";
            cin >> num;

            int lower = num - 10;
            int upper = num + 10;
            vector<int> r_values = { 5, 7, 11, 13, 17, 19, 23, 25, 29, 31 };

            cout << "\nNumber\tGenerated?\tPrime?\tReason\n";
            for (int x = lower; x <= upper; ++x) {
                bool generated = false;
                int r_used = -1, k_used = -1;
                for (int r : r_values) {
                    if ((x - r) % 6 == 0) {
                        int k = (x - r) / 6;
                        if (k >= 0) {
                            generated = true;
                            r_used = r;
                            k_used = k;
                            break;
                        }
                    }
                }

                int reason = -1;
                PrimeStatus status = isPrimeDetailed(x, reason);

                cout << x << "\t";
                if (generated)
                    cout << "Yes (r=" << r_used << ",k=" << k_used << ")\t";
                else
                    cout << "No\t\t";

                if (status == PRIME)
                    cout << "Yes\t\t-\n";
                else if (status == NOT_PRIME_LESS_THAN_2)
                    cout << "No\t\t<2\n";
                else
                    cout << "No\t\tDiv by " << reason << "\n";
            }

            // Final verdict
            int reason = -1;
            PrimeStatus status = isPrimeDetailed(num, reason);
            int found_r = -1, found_k = -1;
            for (int r : r_values) {
                if ((num - r) % 6 == 0) {
                    int k = (num - r) / 6;
                    if (k >= 0) {
                        found_r = r;
                        found_k = k;
                        break;
                    }
                }
            }

            cout << "\n=== Final Verdict for " << num << " ===\n";
            if (status == PRIME) {
                cout << num << " is a PRIME number.\n";
                if (found_r != -1)
                    cout << "Generated by h(k) = " << found_r << " + 6*" << found_k << "\n";
                else
                    cout << "Not generated by any h(k) in current r-set.\n";
            }
            else {
                cout << num << " is NOT prime";
                if (status == NOT_PRIME_LESS_THAN_2)
                    cout << " (less than 2)\n";
                else
                    cout << " (divisible by " << reason << ")\n";

                if (found_r != -1)
                    cout << "It was generated by h(k) = " << found_r << " + 6*" << found_k << "\n";
                else
                    cout << "Not generated by any h(k) in current r-set.\n";
            }
        }
    }
}
